from django.db import models
from django.conf import settings


class WatsonChecklist(models.Model):
    class Status(models.TextChoices):
        DRAFT      = 'DRAFT',      'Draft'
        REVIEWING  = 'REVIEWING',  'Under Review'
        ACCEPTED   = 'ACCEPTED',   'Accepted'
        SUPERSEDED = 'SUPERSEDED', 'Superseded'

    change = models.ForeignKey(
    'changes.ChangeRequest',
    related_name='watson_checklists',
    on_delete=models.CASCADE,
    null=True,
    blank=True,
    )
    status        = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    generated_at  = models.DateTimeField(auto_now_add=True)
    generated_by  = models.CharField(max_length=50, default='watson-mock-v1')
    confidence    = models.FloatField(null=True, blank=True)
    source_notes  = models.TextField(blank=True)
    json_artifact = models.JSONField(default=dict, blank=True)
    accepted_by   = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                       related_name='accepted_checklists', on_delete=models.SET_NULL)
    accepted_at   = models.DateTimeField(null=True, blank=True)
    source_change_id = models.CharField(
        max_length=100, blank=True, db_index=True,
        help_text='Change ID from external source system (protocol API)'
    )
    integration_app = models.ForeignKey(
        'integrations.IntegrationApp',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='checklists',
        help_text='External app that created this checklist via protocol API'
    )

    is_deep_analysis = models.BooleanField(
        default=False,
        help_text='True = generated by Llama 3.3 70B deep analysis, not the governing checklist'
    )
 
    deep_model = models.CharField(
        max_length=100, blank=True,
        help_text='Model used for deep analysis e.g. meta-llama/llama-3-3-70b-instruct'
    )
    
    # jury_verdict stores the comparison result when both models have scored
    jury_verdict = models.CharField(
        max_length=20, blank=True,
        help_text='AGREE|DISAGREE|PARTIAL — set when deep scoring compared to standard scoring'
    )
    class Meta:
        ordering = ['-generated_at']

    def __str__(self):
        return f"Checklist for {self.change.ticket_number} [{self.status}]"


class ChecklistGroup(models.Model):
    """
    A group of checklist items. Can be tied to a specific task or be global.
    group_type: PRE | TASK | POST
    """
    class GroupType(models.TextChoices):
        PRE  = 'PRE',  'Pre-Implementation'
        TASK = 'TASK', 'Task'
        POST = 'POST', 'Post-Implementation'

    checklist  = models.ForeignKey(WatsonChecklist, related_name='groups', on_delete=models.CASCADE)
    code       = models.CharField(max_length=20)
    title      = models.CharField(max_length=200)
    phase      = models.CharField(max_length=30, blank=True)
    group_type = models.CharField(max_length=10, choices=GroupType.choices, default=GroupType.PRE)
    task       = models.ForeignKey('changes.ChangeTask', null=True, blank=True,
                                    related_name='checklist_groups', on_delete=models.SET_NULL)
    order      = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"{self.code}: {self.title}"


class ChecklistItem(models.Model):
    class Acceptance(models.TextChoices):
        PENDING  = 'PENDING',  'Pending'
        ACCEPTED = 'ACCEPTED', 'Accepted'
        REJECTED = 'REJECTED', 'Rejected'
        MODIFIED = 'MODIFIED', 'Modified'

    class ImplResult(models.TextChoices):
        NOT_RUN = 'NOT_RUN', 'Not Run'
        PASS    = 'PASS',    'Pass'
        FAIL    = 'FAIL',    'Fail'
        CAUTION = 'CAUTION', 'Caution'
        SKIPPED = 'SKIPPED', 'Skipped'

    group         = models.ForeignKey(ChecklistGroup, related_name='items', on_delete=models.CASCADE)
    code          = models.CharField(max_length=20)
    description   = models.TextField()
    rationale     = models.TextField(blank=True)
    command_hint  = models.CharField(max_length=500, blank=True)
    caution       = models.TextField(blank=True)
    order         = models.PositiveIntegerField(default=0)

    # CAB acceptance (Authorize phase)
    acceptance      = models.CharField(max_length=10, choices=Acceptance.choices, default=Acceptance.PENDING)
    acceptance_note = models.TextField(blank=True)
    accepted_by     = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                         related_name='accepted_items', on_delete=models.SET_NULL)
    accepted_at     = models.DateTimeField(null=True, blank=True)

    # Implementation — Watson auto-scores by watching activity stream
    impl_result        = models.CharField(max_length=10, choices=ImplResult.choices, default=ImplResult.NOT_RUN)
    impl_evidence      = models.TextField(blank=True)   # the activity/note Watson used
    impl_watson_note   = models.TextField(blank=True)   # Watson's explanation
    impl_validated_at  = models.DateTimeField(null=True, blank=True)
    impl_auto_scored   = models.BooleanField(default=False)  # True = Watson did it passively

    technical_criteria = models.TextField(
    blank=True,
    help_text="Hidden instruction for Phase 2 validator — not shown to implementer"
    )
    confidence_flag = models.CharField(
        max_length=20,
        default='HIGH',
        choices=[
            ('HIGH', 'High Confidence'),
            ('AI-GENERATED', 'AI Generated — Needs Senior Review'),
            ('UNSURE', 'Unsure — Requester Clarification Required'),
        ]
    )
    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"{self.code}: {self.description[:60]}"

 
class CABChallenge(models.Model):
 
    class SourceType(models.TextChoices):
        TASK     = 'TASK',     'Task'
        RUNBOOK  = 'RUNBOOK',  'Runbook / Attachment'
        BACKOUT  = 'BACKOUT',  'Backout Plan'
        SCHEDULE = 'SCHEDULE', 'Schedule / Window'
        SCOPE    = 'SCOPE',    'Declared Scope'
        CI       = 'CI',       'Configuration Item'
        GENERAL  = 'GENERAL',  'General'
 
    class Severity(models.TextChoices):
        CRITICAL = 'CRITICAL', 'Critical'
        HIGH     = 'HIGH',     'High'
        MEDIUM   = 'MEDIUM',   'Medium'
 
    class Status(models.TextChoices):
        OPEN       = 'OPEN',       'Open — awaiting justification'
        JUSTIFIED  = 'JUSTIFIED',  'Justified — awaiting Watson evaluation'
        SATISFIED  = 'SATISFIED',  'Satisfied — Watson accepted justification'
        ESCALATED  = 'ESCALATED',  'Escalated — justification insufficient'
 
    # Scope
    change       = models.ForeignKey(
        'changes.ChangeRequest',
        on_delete=models.CASCADE,
        related_name='cab_challenges',
    )
    linked_item  = models.ForeignKey(
        'watson.ChecklistItem',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='cab_challenges',
        help_text='Checklist item this challenge maps to — updated on satisfaction',
    )
 
    # Challenge content
    source_type          = models.CharField(max_length=20, choices=SourceType.choices)
    source_ref           = models.CharField(
        max_length=200,
        help_text='Human-readable source reference e.g. "Task 2", "Runbook Step 4", "Backout Plan"'
    )
    finding              = models.TextField(
        help_text='Specific observation Watson made — named evidence, not vague'
    )
    severity             = models.CharField(max_length=10, choices=Severity.choices)
    acceptance_criteria  = models.TextField(
        help_text='Exact sub-criteria Watson needs satisfied — numbered list'
    )
    order                = models.PositiveSmallIntegerField(default=0)
 
    # Resolution
    status               = models.CharField(
        max_length=12, choices=Status.choices, default=Status.OPEN
    )
    justification        = models.TextField(
        blank=True,
        help_text='Response provided by CAB member or presenter'
    )
    resolution_note      = models.TextField(
        blank=True,
        help_text='Watson verdict — what was satisfied or what remains insufficient'
    )
    resolved_at          = models.DateTimeField(null=True, blank=True)
    resolved_by          = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='resolved_cab_challenges',
    )
 
    # Audit
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)
    resubmit_count = models.PositiveSmallIntegerField(
        default=0,
        help_text='How many times this challenge has been resubmitted'
    )
 
    class Meta:
        ordering = ['order', '-severity', 'source_type']
 
    def __str__(self):
        return f"{self.change.ticket_number} | {self.source_ref} | {self.severity} | {self.status}"
 
    @property
    def is_resolved(self):
        return self.status in (self.Status.SATISFIED, self.Status.ESCALATED)
 
    @property
    def severity_order(self):
        return {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2}.get(self.severity, 3)
 