"""
IBM watsonx.ai engine — calls Granite via the watsonx.ai REST API.

Required settings (set in .env or environment):
    WATSON_MODE=ibm
    WATSON_API_KEY=<your IBM Cloud API key>
    WATSON_URL=https://eu-de.ml.cloud.ibm.com   (or your region)
    WATSON_PROJECT_ID=<your watsonx project ID>

Optional:
    WATSON_MODEL_ID=ibm/granite-3-3-8b-instruct   (default)
    WATSON_MAX_TOKENS=4000
"""

import json
import logging
import re
import time
import requests
from django.conf import settings
from .base import WatsonEngineBase
from .prompts import (CHECKLIST_SYSTEM, CHECKLIST_USER,
                       SCORING_SYSTEM, SCORING_USER)
from .attachment_extractor import build_attachments_section

logger = logging.getLogger(__name__)

# ── IBM IAM token cache ────────────────────────────────────────────────────
_token_cache = {'token': None, 'expires_at': 0}

IAM_URL = 'https://iam.cloud.ibm.com/identity/token'


def _get_iam_token(api_key: str) -> str:
    """Fetch (or return cached) IBM IAM bearer token."""
    now = time.time()
    if _token_cache['token'] and _token_cache['expires_at'] > now + 60:
        return _token_cache['token']

    resp = requests.post(IAM_URL, data={
        'grant_type': 'urn:ibm:params:oauth:grant-type:apikey',
        'apikey': api_key,
    }, headers={'Content-Type': 'application/x-www-form-urlencoded'}, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    _token_cache['token'] = data['access_token']
    _token_cache['expires_at'] = now + int(data.get('expires_in', 3600))
    return _token_cache['token']


# ── JSON extraction ────────────────────────────────────────────────────────
def _extract_json(text: str) -> dict:
    """
    Robustly extract JSON from Watson response.
    Handles markdown fences, preamble text, trailing content,
    and truncated responses (token limit hit mid-stream).
    """
    if not text:
        raise ValueError("Empty response from Watson")

    # Strip markdown fences
    text = re.sub(r'```(?:json)?\s*', '', text).strip()

    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Find outermost {...}
    start = text.find('{')
    end   = text.rfind('}')
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            pass

    # JSON was truncated mid-stream (token limit hit) — attempt recovery.
    # Walk backwards from the end to find the last parseable subset,
    # balancing braces as needed.
    if start != -1:
        fragment = text[start:]
        for close_pos in range(len(fragment) - 1, 0, -1):
            if fragment[close_pos] == '}':
                candidate = fragment[:close_pos + 1]
                opens  = candidate.count('{')
                closes = candidate.count('}')
                if closes < opens:
                    candidate += '}' * (opens - closes)
                try:
                    parsed = json.loads(candidate)
                    logger.warning("Watson JSON was truncated — recovered partial response")
                    return parsed
                except json.JSONDecodeError:
                    continue

    raise ValueError(
        f"Could not parse JSON from Watson response: {text[:300]}"
    )


def _validate_checklist(data: dict, expected_task_count: int = 0) -> dict:
    """
    Validate and normalise checklist response schema.
    Enforces P6: every task must have a corresponding TASK group.
    """
    if 'groups' not in data:
        raise ValueError("Watson response missing 'groups' key")
 
    for g in data['groups']:
        g.setdefault('code', 'UNK')
        g.setdefault('title', g['code'])
        g.setdefault('phase', '')
        g.setdefault('group_type', 'PRE')
        g.setdefault('task_ref', None)
        g.setdefault('items', [])
 
        for item in g['items']:
            item.setdefault('code', f"{g['code']}.?")
            item.setdefault('description', '')
            item.setdefault('rationale', '')
            item.setdefault('command_hint', '')
            item.setdefault('caution', '')
            item.setdefault('technical_criteria', '')
            item.setdefault('confidence_flag', 'HIGH')
 
    data.setdefault('domain', 'generic')
    data.setdefault('confidence', 0.8)
    data.setdefault('source_notes', 'Generated by IBM watsonx.ai Granite')
    data.setdefault('model', getattr(settings, 'WATSON_MODEL_ID',
                                     'ibm/granite-3-3-8b-instruct'))
 
    # P6 enforcement — check task coverage
    if expected_task_count > 0:
        actual_task_groups = len([
            g for g in data['groups']
            if g.get('group_type') == 'TASK'
        ])
        if actual_task_groups < expected_task_count:
            missed = expected_task_count - actual_task_groups
            logger.warning(
                f"P6 violation: Watson generated {actual_task_groups} TASK groups "
                f"but change has {expected_task_count} tasks. "
                f"Missing {missed} task group(s). Flagging checklist."
            )
            # Flag all items as needing review when P6 is violated
            for g in data['groups']:
                for item in g['items']:
                    if item.get('confidence_flag') == 'HIGH':
                        item['confidence_flag'] = 'AI-GENERATED'
            data['source_notes'] = (
                f"[P6 WARNING: {missed} task(s) may not have checklist coverage. "
                f"Senior review required.] " + data.get('source_notes', '')
            )
            data['confidence'] = min(data.get('confidence', 0.8), 0.6)
 
    return data

def _validate_scoring(data: dict) -> dict:
    """Validate and normalise scoring response."""
    result = data.get('result', 'CAUTION').upper()
    if result not in ('PASS', 'FAIL', 'CAUTION'):
        result = 'CAUTION'
    return {
        'result':             result,
        'watson_note':        data.get('watson_note', 'Watson could not determine result.'),
        'confidence':         float(data.get('confidence', 0.5)),
        'principles_checked': data.get('principles_checked', {}),
    }


# ── IBM Engine ─────────────────────────────────────────────────────────────
class IBMWatsonEngine(WatsonEngineBase):

    def __init__(self):
        self.api_key    = settings.WATSON_API_KEY
        self.url        = settings.WATSON_URL.rstrip('/')
        self.project_id = settings.WATSON_PROJECT_ID
        self.model_id   = getattr(settings, 'WATSON_MODEL_ID',
                                  'ibm/granite-3-3-8b-instruct')
        self.max_tokens = int(getattr(settings, 'WATSON_MAX_TOKENS', 8000))

        if not self.api_key:
            raise RuntimeError("WATSON_API_KEY is not set")
        if not self.project_id:
            raise RuntimeError("WATSON_PROJECT_ID is not set")

    def _call(self, system_prompt: str, user_prompt: str) -> str:
        """POST to watsonx.ai /ml/v1/text/generation endpoint."""
        token = _get_iam_token(self.api_key)

        endpoint = f"{self.url}/ml/v1/text/generation?version=2023-05-29"
        payload = {
            "model_id":   self.model_id,
            "project_id": self.project_id,
            # Granite 3.x chat format
            "input": (
                f"<|start_of_role|>system<|end_of_role|>"
                f"{system_prompt}"
                f"<|end_of_text|>"
                f"<|start_of_role|>user<|end_of_role|>"
                f"{user_prompt}"
                f"<|end_of_text|>"
                f"<|start_of_role|>assistant<|end_of_role|>"
            ),
            "parameters": {
                "decoding_method":    "greedy",
                "max_new_tokens":     self.max_tokens,
                "repetition_penalty": 1.05,
                "stop_sequences":     ["}\n}}\n", "}\n}\n}"],
            }
        }

        logger.info(
            f"Calling watsonx.ai: model={self.model_id}, "
            f"prompt_len={len(payload['input'])}"
        )

        resp = requests.post(
            endpoint,
            json=payload,
            headers={
                'Authorization': f'Bearer {token}',
                'Content-Type':  'application/json',
                'Accept':        'application/json',
            },
            timeout=120,
        )

        if not resp.ok:
            logger.error(f"Watson API error {resp.status_code}: {resp.text[:500]}")
            resp.raise_for_status()

        data      = resp.json()
        generated = data.get('results', [{}])[0].get('generated_text', '')
        logger.info(
            f"Watson response: {len(generated)} chars, "
            f"stop_reason={data.get('results', [{}])[0].get('stop_reason', '')}"
        )
        return generated

    # ── Prompt context builders ────────────────────────────────────────────

    def _build_tasks_section(self, tasks: list) -> str:
        if not tasks:
            return "No tasks defined."
        lines = []
        for i, t in enumerate(tasks, 1):
            ci_info = f" | CI: {t['ci_name']} ({t['ci_type']})" if t.get('ci_name') else ''
            lines.append(f"Task {i} [ID:{t.get('id','')}]: {t['short_description']}{ci_info}")
            if t.get('description'):
                # Cap task descriptions — they contain commands Watson needs but
                # long runbooks waste tokens. 1000 chars covers ~4-5 numbered steps.
                desc = t['description']
                if len(desc) > 1000:
                    desc = desc[:1000] + '... [TRUNCATED]'
                lines.append(f"  Details: {desc}")
            if t.get('status'):
                lines.append(f"  Status: {t['status']}")
        return '\n'.join(lines)

    def _build_cis_section(self, cis: list) -> str:
        if not cis:
            return "No CIs specified."
        lines = []
        for ci in cis:
            env          = ci.get('environment', '')
            criticality  = ci.get('business_criticality', '')
            requires_p5  = (
                env.lower() in ('production', 'prod') or
                criticality.lower() in ('critical', 'high')
            )
            parts = [
                ci.get('name', ''),
                ci.get('ci_type', ''),
                env,
                ci.get('os', ''),
                f"criticality={criticality}",
                f"requires_p5={'YES' if requires_p5 else 'NO'}",
            ]
            lines.append(' | '.join(p for p in parts if p))
        return '\n'.join(lines)

    def _build_evidence_section(self, activity: list) -> str:
        if not activity:
            return "No activity recorded."
        lines = []
        for entry in activity[:30]:
            ts = entry.get('created_at', '')[:19]
            lines.append(
                f"[{ts}] {entry.get('action_type', '')} — "
                f"{entry.get('message', '')[:200]}"
            )
        return '\n'.join(lines)

    # ── Public interface ───────────────────────────────────────────────────

    def generate_checklist(self, change_data: dict) -> dict:
        tasks = change_data.get('tasks', [])
        cis   = change_data.get('cis', [])

        # Use the CAB-approved change window for P1 temporal proof,
        # not the planned execution slot.
        change_window = (
            f"{change_data.get('change_window_start', 'Not specified')} "
            f"to {change_data.get('change_window_end', 'Not specified')}"
        )

        user_prompt = CHECKLIST_USER.format(
            ticket_number       = change_data.get('ticket_number', 'N/A'),
            short_description   = change_data.get('short_description', ''),
            change_type         = change_data.get('change_type', 'Normal'),
            priority            = change_data.get('priority', '3'),
            risk_level          = change_data.get('risk_level', 'Medium'),
            impact              = change_data.get('impact', ''),
            category            = change_data.get('category', ''),
            service             = change_data.get('service', ''),
            change_window       = change_window,
            description         = self._truncate_context(change_data.get('description', ''), 500),
            implementation_plan = self._truncate_context(change_data.get('implementation_plan', ''), 600),
            rollback_plan       = self._truncate_context(change_data.get('rollback_plan', ''), 300),
            test_plan           = self._truncate_context(change_data.get('test_plan', ''), 300),
            task_count          = len(tasks),
            tasks_section       = self._build_tasks_section(tasks),
            ci_count            = len(cis),
            cis_section         = self._build_cis_section(cis),
            attachments_section = build_attachments_section(
                change_data.get('attachments_with_paths', [])
            ),
        )

        try:
            raw    = self._call(CHECKLIST_SYSTEM, user_prompt)
            data   = _extract_json(raw)
            result = _validate_checklist(data, expected_task_count=len(tasks))
            result['model'] = self.model_id
            return result
        except Exception as e:
            logger.exception(f"Watson checklist generation failed: {e}")
            raise

    def passive_score(self, change_data: dict, checklist_items: list) -> list:
        """Score items one at a time — batch would exceed context window."""
        results = []

        activity_text    = self._build_evidence_section(change_data.get('activity', []))
        attachments_text = ', '.join(
            a.get('filename', '') for a in change_data.get('attachments', [])
        ) or 'None'

        # P5: Django already knows CI risk — don't make Watson guess
        ci_env      = change_data.get('primary_ci_env', '').lower()
        ci_name     = change_data.get('primary_ci_name', 'Not specified')
        requires_p5 = (
            ci_env in ('production', 'prod') or
            change_data.get('risk_level', '').lower() in ('high', 'critical')
        )
        requires_p5_str = (
            'YES — secondary sign-off artifact required'
            if requires_p5 else 'NO'
        )

        # P1: use the CAB-approved window, not the planned execution slot
        change_window = (
            f"{change_data.get('change_window_start', 'Not specified')} "
            f"to {change_data.get('change_window_end', 'Not specified')}"
        )

        for item in checklist_items:
            if item.get('acceptance') not in ('ACCEPTED', 'MODIFIED'):
                continue
            if item.get('impl_result') not in ('NOT_RUN', 'CAUTION'):
                continue
            
            time.sleep(1.0)

            linked_status = item.get('linked_task_status', '')
            task_status   = (
                f"Linked task status: {linked_status}"
                if linked_status else "No linked task."
            )

            user_prompt = SCORING_USER.format(
                code               = item.get('code', ''),
                description        = item.get('description', ''),
                rationale          = item.get('rationale', ''),
                technical_criteria = item.get('technical_criteria', 'No specific criteria defined.'),
                change_window      = change_window,
                requires_p5        = requires_p5_str,
                ci_name            = ci_name,
                task_status        = task_status,
                evidence           = activity_text,
                attachments        = attachments_text,
            )

            try:
                raw    = self._call(SCORING_SYSTEM, user_prompt)
                data   = _extract_json(raw)
                scored = _validate_scoring(data)
                results.append({
                    'item_id':            item['id'],
                    'result':             scored['result'],
                    'watson_note':        scored['watson_note'],
                    'confidence':         scored['confidence'],
                    'principles_checked': scored['principles_checked'],
                    'evidence_used':      activity_text[:300],
                    'auto_scored':        True,
                })
            except Exception as e:
                logger.warning(f"Could not score item {item.get('code')}: {e}")
                continue

        return results
    

    def _truncate_context(self, text: str, limit: int = 1000) -> str:
        """
        Prevent large runbooks from consuming the token budget.
        Appends a marker so Watson knows content was cut — not a silent truncation.
        """
        if not text:
            return 'Not provided'
        if len(text) > limit:
            return text[:limit] + '... [TRUNCATED]'
        return text

